#!/bin/bash
ocamlc -c types.mli
ocamlc -c types.ml
ocamllex lexer.mll
ocamlyacc parser.mly
ocamlc -c  parser.mli
ocamlc -c  lexer.ml
ocamlc -c  parser.ml
ocamlc -c  stats.ml
ocamlc -o  stats  lexer.cmo parser.cmo  stats.cmo

#mv ./render6 ./

#clean
rm *.cmi
rm *.cmo
# rm *.cmx
# rm *.o
rm lexer.ml
rm parser.ml
rm parser.mli

# ozan$ ls `ocamlc -where`/graphics*
