#!/bin/bash
ocamlopt -c types.mli
ocamlopt -c types.ml
ocamllex lexer.mll
ocamlyacc parser.mly
ocamlopt -c  parser.mli
ocamlopt -c  lexer.ml
ocamlopt -c  parser.ml
ocamlopt -c  radius.ml
ocamlopt -o  radius  lexer.cmx parser.cmx  radius.cmx

rm *.cmx
rm *.o
rm lexer.ml
rm parser.ml
rm parser.mli
